name: Bug Report
description: Report a bug in the OJS Go SDK
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a client with ...
        2. Call Enqueue with ...
        3. Observe error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`.
      placeholder: go1.24.0 darwin/arm64
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Version of ojs-go-sdk.
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: OJS Server Version
      description: Version and backend of the OJS server (if applicable).
      placeholder: ojs-backend-redis v0.1.0
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots.
    validations:
      required: false
